version: 2

sources:
  - name: airbnb
    schema: raw
    description: "Raw data ingested from external sources like DMS, Glue, or Kafka."
    tables:
      - name: listings
        identifier: raw_listings 
        description: "Raw Airbnb listings table from ingestion layer."
        config:
          freshness:
            warn_after: { count: 1, period: hour }
            error_after: { count: 12, period: hour }
          loaded_at_field: date
        columns:
          - name: id
            description: "Unique ID of the listing"
            tests:
              - unique
              - not_null
          - name: name
            description: "Title of the listing"
          - name: room_type
            description: "Type of the room offered"
          - name: price
            description: "Listing price in USD"
          - name: created_at
            description: "Timestamp when listing was created"
          - name: updated_at
            description: "Timestamp when listing was last updated"

      - name: reviews
        identifier: raw_reviews
        description: "User-generated reviews associated with listings."
        config:
          freshness:
            warn_after: { count: 1, period: hour }
            error_after: { count: 12, period: hour }
          loaded_at_field: date
        columns:
          - name: listing_id
            description: "ID of the associated listing"
          - name: date
            description: "Date of the review"
          - name: reviewer_name
            description: "Name of the reviewer"
          - name: comments
            description: "Review text"
          - name: sentiment
            description: "Pre-labeled sentiment of the review"
